### ISSUE TITLE
Tag your up-to-date changes

### ISSUE THREAD

**Issue by tyloo** [genesis-global/salesforce-bundle#11]
Hello,

Because of the fact that you didn't tagged a version since 2017, we are now forced to use dev-master in our composer.json. Is it possible to regularly tag your changes please ? https://semver.org FYI

**Comment by coderaf** [comment]
There you are https://github.com/genesis-global/salesforce-bundle/releases/tag/1.3.0
The most up to date release, notes what included in tag description.

**Comment by tyloo** [comment]
Thanks a lot! 🤗

**Comment by Taluu** [comment]
Would it be possible to update packagist ? Thanks.
