### ISSUE TITLE
Update packagist information

### ISSUE THREAD

**Issue by Taluu** [genesis-global/salesforce-bundle#12]
Would it be possible to update packagist ? Thanks.

_Originally posted by @Taluu in https://github.com/genesis-global/salesforce-bundle/issues/11#issuecomment-534555410_

**Comment by coderaf** [comment]
Yes we are aware of need. I cant do it by myself so it waits on list of priorities to do.

**Comment by coderaf** [comment]
packagist is updated now.

**Comment by Taluu** [comment]
Thanks. Would it be possible to let the hook work ? :}

**Comment by SiliconMind** [comment]
@taluu that’s up to the gods of synchronisation. The hook was set up but it stopped working for some reason and we had to disconnect packagist from github and connect it again.

**Comment by Taluu** [comment]
Actually there was a change some time ago, as github stopped supporting services, so packagist had to migrate to an app or hooks (can't remember exactly).
