### ISSUE TITLE
Question : can we call Salesforce custom webservices implemented as REST APIs ?

### ISSUE THREAD

**Issue by AltiusRupert** [genesis-global/salesforce-bundle#13]
If I declare a Salesforce Apex class as a custom REST API webservice, ca I call this webservice from salesforce-bundle ?

**Comment by coderaf** [comment]
You can always overwrite `salesforce.service` definition and put your class as `salesforce.client` but you would need to wrap your class with something that implement `SalesforceClientInterface`

**Comment by AltiusRupert** [comment]
Thanks, we will have a look at your idea.
