### ISSUE TITLE
Problems with config

### ISSUE THREAD

**Issue by echizent4** [genesis-global/salesforce-bundle#5]
Hi, I am new using SF bundles,
You know how can get this info:
        endpoint: "https://login.salesforce.com/"
        client_id: ""
        client_secret: ""
        security_token: ''
I allways make sistem with username and password login. 
Thx

**Comment by coderaf** [comment]
Hey, you got some info  in salesforce rest api documentation here https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_defining_remote_access_applications.htm

You probably could read some more, to understand better how it works too.
